# Usa la imagen base de pgAdmin 4
FROM dpage/pgadmin4

# Copia las variables de entorno definidas en el archivo .env
ARG PGADMIN_DEFAULT_EMAIL
ARG PGADMIN_DEFAULT_PASSWORD

# Configura las variables de entorno para el correo electrónico y la contraseña predeterminados
ENV PGADMIN_DEFAULT_EMAIL $PGADMIN_DEFAULT_EMAIL
ENV PGADMIN_DEFAULT_PASSWORD $PGADMIN_DEFAULT_PASSWORD
