# Generated by Django 5.0.4 on 2024-04-19 17:2

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auction_id', models.AutoField(primary_key=True, serialize=False)),
                ('auction_name', models.CharField(max_length=255, verbose_name='Nombre de la subasta')),
                ('auction_description', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
            options={
                'db_table': 'auctions',
                'indexes': [models.Index(fields=['start_date'], name='auctions_start_d_93d083_idx'), models.Index(fields=['end_date'], name='auctions_end_dat_34dee3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('artwork_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('year_created', models.IntegerField()),
                ('dimensions', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('minimum_bid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('status', models.CharField(default='active', max_length=20)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction_app.auction')),
            ],
            options={
                'db_table': 'artworks',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_timestamp', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction_app.artwork')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction_app.auction')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction_app.customer')),
            ],
            options={
                'db_table': 'bids',
            },
        ),
    ]
