# Generated by Django 4.2.11 on 2024-04-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_alter_artwork_status_alter_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_name',
            field=models.CharField(max_length=255, verbose_name='Auction Name'),
        ),
    ]
