# Generated by Django 4.2.11 on 2024-05-02 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_alter_artwork_status_alter_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_type',
            field=models.CharField(default='ID', max_length=50),
        ),
    ]
