# Generated by Django 4.2.13 on 2024-06-05 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_alter_artwork_status_alter_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_type',
            field=models.CharField(max_length=50),
        ),
    ]
