# Generated by Django 4.2.13 on 2024-06-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0003_alter_admin_email_alter_auction_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
