# Generated by Django 4.2.11 on 2024-05-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0004_admin_is_admin_alter_admin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_type',
            field=models.CharField(max_length=50),
        ),
    ]
